tests: drivers: retained_mem: fix compilation.
Fixes the compilation error:

    error: 'static' is not at beginning of declaration
    [-Werror=old-style-declaration]

Signed-off-by: Samuel Coleman <samuel.coleman@rbr-global.com>
(cherry picked from commit f13abe5f10864e532fd81e0433a4e3ba3cd60545)